### ISSUE TITLE
Linearelasticity and Nonlinearelasticity not working

### ISSUE THREAD

**Issue by physici** [physici/ElmerSalome#31]
When moving the Linearelasticity.xml or Nonlinearelasticity.xml from edf-extra to edf, the plugin stops working.

Following error is created in the console of Salome.
`CRITICAL [PluginsManager] : Error while loading plugins from file C:\Downloads\SALOME-8.3.0-WIN64\MODULES\GUI\RELEASE\GUI_INSTALL\share/salome/plugins\gui\salome_plugins.py
Traceback (most recent call last):
  File "C:\Downloads\SALOME-8.3.0-WIN64\MODULES\GUI\RELEASE\GUI_INSTALL\lib\python2.7\site-packages\salome\salome_pluginsmanager.py", line 284, in importPlugins
    execfile(plugins_file,globals(),{})
  File "C:\Downloads\SALOME-8.3.0-WIN64\MODULES\GUI\RELEASE\GUI_INSTALL\share/salome/plugins\gui\salome_plugins.py", line 55, in <module>
    main = ewh.ElmerWindowHandler()
  File "C:\Downloads\SALOME-8.3.0-WIN64\MODULES\GUI\RELEASE\GUI_INSTALL\share/salome/plugins\gui\ElmerSalome\elmer_window_handler.py", line 85, in __init__
    self._xmlMerge(path_edfs)
  File "C:\Downloads\SALOME-8.3.0-WIN64\MODULES\GUI\RELEASE\GUI_INSTALL\share/salome/plugins\gui\ElmerSalome\elmer_window_handler.py", line 1170, in _xmlMerge
    data = et.parse(xml_file).getroot()
  File "C:\Downloads\SALOME-8.3.0-WIN64\PRODUCTS\python-2.7.10\Lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Downloads\SALOME-8.3.0-WIN64\PRODUCTS\python-2.7.10\Lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\Downloads\SALOME-8.3.0-WIN64\PRODUCTS\python-2.7.10\Lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Downloads\SALOME-8.3.0-WIN64\PRODUCTS\python-2.7.10\Lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 310, column 142]`

**Comment by physici** [comment]
A bad character encoding is in the description of the Youngs modulus. In both files the following section needs to be deleted and typed in exactly the same.
`6 x 6 (3D) or 4 x 4`

Linearelasticity.xml: line 310, column 142
Nonlinearelasticity.xml: line 202, column 142
